# MPV Concentration Rate
# Defines the MPV concentration rate as a percentage. 100% indicates full concentration.
mpv_concentration_rate_percent: 50.0 
# MPV Microinverter Apparent Power (gamma1) [600, 800, 1000]
# Sets the maximum apparent power for the MPV microinverter at 600 Watts. Alternatives include 800W and 1000W.
mpv_inverter_apparent_power_watt: 600 #  (gamma1)
# MPV Solar Cell Capacity (gamma2) [800, 1200, 1600, 2000]
# Specifies the maximum power capacity of the MPV solar cells at 800 Watts, equivalent to 2 panels.
# Other options are 1200W (3 panels), 1600W (4 panels), and 2000W (5 panels).
mpv_solar_cell_capacity_watt: 800 # (gamma2) 
advanced_plot:
  annotation_size: 1.05
  bus_color: blue
  bus_size: 0.65
  distance_factor: 75.0
  ext_grid_color: k
  ext_grid_size: 1.0
  factor: 1.0
  line_color: grey
  line_width: 3.0
  load_size: 1.05
  mpv_sgen_size: 0.55
  orientation_loads: 1.0
  orientation_mpv_sgens: 0.625
  orientation_sgens: 0.78125
  orientation_storage: 1.25
  plot_annotation: true
  plot_loads: true
  plot_mpv_sgens: true
  plot_sgens: true
  plot_storages: true
  scale_size: true
  sgen_color: k
  sgen_size: 1.05
  storage_color: k
  storage_size: 1.0
  trafo_color: k
  trafo_size: 1.05
basic_plot:
  annotation_size: 1.05
  bus_color: blue
  bus_size: 0.65
  distance_factor: 100.0
  ext_grid_color: k
  ext_grid_size: 1.0
  factor: 1.0
  line_color: grey
  line_width: 3.0
  load_size: 1.05
  mpv_penetration_rate_percent: 100.0
  mpv_sgen_size: 0.55
  orientation_loads: 1.0
  orientation_mpv_sgens: 0.625
  orientation_sgens: 0.78125
  orientation_storage: 1.25
  plot_annotation: false
  plot_loads: false
  plot_mpv_sgens: false
  plot_sgens: false
  plot_storages: false
  scale_size: true
  sgen_color: k
  sgen_size: 1.05
  storage_color: k
  storage_size: 1.0
  trafo_color: k
  trafo_size: 1.05
main_advanced_plot:
  annotation_size: 1.05
  bus_color: blue
  bus_size: 0.65
  distance_factor: 75.0
  ext_grid_color: k
  ext_grid_size: 1.0
  factor: 1.0
  line_color: grey
  line_width: 3.0
  load_size: 1.05
  mpv_sgen_size: 0.55
  orientation_loads: 1.0
  orientation_mpv_sgens: 0.625
  orientation_sgens: 0.78125
  orientation_storage: 1.25
  plot_annotation: true
  plot_loads: true
  plot_mpv_sgens: false
  plot_sgens: true
  plot_storages: true
  scale_size: true
  sgen_color: k
  sgen_size: 1.05
  storage_color: k
  storage_size: 1.0
  trafo_color: k
  trafo_size: 1.05
multi_plot_settings:
  num_codes: 6
  num_cols: 2
  num_rows: 3
  num_scenarios: 3
  selected_distance_factor: 100.0
  selected_factor: 1.0
path:
  base_path: C:\Users\ii6824\Documents\PIDE\helper
  cfg_default_plot_path: C:\Users\ii6824\Documents\PIDE\yaml\default_config_grid_manage_der.yaml
  cfg_user_plot_path: C:\Users\ii6824\Documents\PIDE\yaml\user_plot_config_grid.yaml
  output_latex_path: \paper_plot\Appendix-C-05-Configurations012-tab-345
  output_plot_path: \paper_plot\
  parent_path: C:\Users\ii6824\Documents\PIDE
  save_output_latex_path: C:\Users\ii6824\Documents\PIDE\paper_plot\Appendix-C-05-Configurations012-tab-345
  save_output_plot_path: C:\Users\ii6824\Documents\PIDE\paper_plot\
simple_plot:
  ext_grid_color: k
  ext_grid_size: 2.5
  load_size: 2.5
  plot_loads: true
  plot_sgens: true
  sgen_size: 2.5
  trafo_size: 2.5
